In [8]:
a = [1,2,3,4]
a * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
import numpy as np
a = [1,2,3,4]
b = np.array(a)
b * 2

array([2, 4, 6, 8])

In [11]:
b**2

array([ 1,  4,  9, 16])

In [13]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8])
c = np.array([9,10,11,12,13])
# print(a+b) will not work
print(a+c)

[10 12 14 16 18]


In [15]:
x = np.array([[1,2],[3,4]]) # Integer values
x

array([[1, 2],
       [3, 4]])

In [16]:
x = np.array([[1,2],[3,4]], dtype=np.float64) # Integer values
x

array([[1., 2.],
       [3., 4.]])

In [19]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
from skimage import io
img = io.imread('../sample/1.png')
print(type(img))

<class 'numpy.ndarray'>


In [25]:
a = np.ones_like(img)
a.shape # same dimension as image

(1706, 3020, 4)

In [44]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f"shape: {np.shape(a)}\n")
print(a , '\n')
print(a[:2]) # row 0:2

shape: (3, 4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
print(a[:2,1:3]) # row 0:2 and column 1:3

[[2 3]
 [6 7]]


In [49]:
print(f"a\n {a}\n")

column_sum = np.sum(a, axis=0)
print(f"column_sum\n {column_sum}\n")
row_sum = np.sum(a, axis=1)
print(f"row_sum\n {row_sum}\n")
max_value = np.max(a)
print(f"max_value\n {max_value}\n")

transposed = a.T
print(f"transposed\n {transposed}\n")

a
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

column_sum
 [15 18 21 24]

row_sum
 [10 26 42]

max_value
 12

transposed
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

